### PR TITLE
Adding FK constraints to database to protect patients from misdiagnosis

### PR DESCRIPTION
**Pull request by pydanny**
Simple database migration to industry standard foreign key constraints.

### CODE REVIEW

**Comment by pydanny** [comment]
Resolves #9, #11, #12, #13

**Comment by thinmanj** [comment]
Looks good to be merged, implements FK

**Comment by kamranhossain** [comment]
@pydanny  Great PR. Hope, it will be merged.

**Comment by MarlonJD** [comment]
It has to be merge immediately

**Pull request merged**
